### ISSUE TITLE
Incorrect PHPDoc Formatting

### ISSUE THREAD

**Issue by Jubeki** [laravel/pint#1]
- Pint Version: 0.1.0
- PHP Version: 8.1.6

### Description:
The Laravel Code Style has the following style throughout the source code:

#### `laravel_phpdoc_alignment`
After `@param` should be two spaces then a `type-hint` then another two spaces and then the `$variable`
```diff
  /**
   * Here is a description for what the function does
-  * @param string $foo
+  * @param  string  $foo
   * @return string
   */
  public function bar($foo) {}
```

#### `laravel_phpdoc_order`
First should be the `description` after that `@param` then `@return` and at last `@throws`
The default rule `phpdoc_order` has a different order: `description`, `@param`, `@throws`, `@return`
```diff
  /**
   * Here is a description for what the function does
   * @param string $foo
   * @param  string  $foo
-  * @throws \Exception
   * @return string
+  * @throws \Exception
   */
  public function bar($foo) {}
```

#### `laravel_phpdoc_seperation `
Between each group of tags should be an empty line for seperation. `@param` and `@return` are always of the same group and are not to be seperated with an empty line.
The default behaviour for `phpdoc_seperation` is also an empty line between `@param` and `@return`.
```diff
  /**
   * Here is a description for what the function does
+  *
   * @param string $foo
   * @param  string  $foo
-  *
   * @return string
+  *
   * @throws \Exception
   */
  public function bar($foo) {}
```

### Steps To Reproduce:
1. Create Fixtures for the example
2. Run pint
3. Check the result remains unchanged

### Possible Solution
Since there are no default rules for PHP-CS-Fixer I created custom ones.
There are three Fixers for PHP-CS-Fixer which could be included here.
https://github.com/Jubeki/laravel-code-style/tree/main/src/Fixers

Do you have an interest in a PR?

**Comment by Jubeki** [comment]
Sure, I will do that.

**Comment by nunomaduro** [comment]
https://github.com/laravel/pint/pull/3

**Comment by jesseleite** [comment]
>After @param should be two spaces then a type-hint then another two spaces and then the $variable

Just a quick question on Laravel's docblock style with the double spaces thing. I notice it's correcting to 4 spaces on a few of our docblocks because we specify a @param without a type...

![image](https://user-images.githubusercontent.com/5187394/177210732-ff1bc658-bd62-4534-b03a-35e3ff7275e7.png)

Is a type required to be a valid docblock?
