### ISSUE TITLE
Pint does not honor `exclude` and `notPath` rules in `pint.json` when passed a list of files

### ISSUE THREAD

**Issue by CalebDW** [laravel/pint#105]
- Pint Version: 1.1.1
- PHP Version: 8.1.9

### Description:
I have a pre-commit hook that grabs the list of files to be committed from git and passes them to Pint as a list of command line arguments. However, doing this causes Pint to "fix" the files even if some of them are on the exclude lists in `pint.json`  (which often breaks them, hence why they were excluded in the first place).

I'm not sure what the intended behaviour was...it could be that the intended behaviour was to override the exclude lists when explicitly passing Pint a file or list of files. However, I could also see some benefit in respecting the exclude lists when passing files to Pint. To clarify the behaviour (and allow for both options), perhaps a `-f` argument could be added to Pint which would force Pint to fix a file even if it's on the exclude lists?

### Steps To Reproduce:
1. Add either a path or file to the `exclude` or `notPath` fields in `pint.json`, respectively.
2. Pass a file (or list of files) to Pint (`pint <file_1> <file_2> ...`) which would normally be excluded when running `pint` by itself.

**Comment by driesvints** [comment]
This is the intended behavior. Passing files explicitly will cause them to be formatted.
