### ISSUE TITLE
Add an artisan command to run pint

### ISSUE THREAD

**Issue by tkaravou** [laravel/pint#106]
It would be nice if we can call pint using a command like `artisan pint` or similar. Running pint using `vendor/bin/pint` isn't very Laravel-like.

**Comment by driesvints** [comment]
Thanks for your suggestion. Right now we don't have any plans for this.

**Comment by Muhammad-Sarfaraz** [comment]
> Thanks for your suggestion. Right now we don't have any plans for this.

any specific reason? It feels wired and less friendly, `"./vendor/bin/pint"`

**Comment by Azizul109** [comment]
> For those seeking elegant solutions: Consider adding the following code snippet to the "scripts" section of your composer.json file.
> 
> ```
> "scripts": {
>     "pint": [
>         "./vendor/bin/pint"
>     ],
>     // Other scripts...
> }
> ```
> 
> Then,run:
> 
> ```
> composer pint
> ```

Superb solution!!!
