### ISSUE TITLE
pint.json is not being used

### ISSUE THREAD

**Issue by anchetaWern** [laravel/pint#115]
- Pint Version: 1.2
- PHP Version: 8.1

### Description:

Not sure if I just didn't read the documentation enough or I missed some detail somewhere else, but I was expecting that when you add a `pint.json` file on the root directory of the project it will automatically be used when you run pint.
But it seems like it doesn't. I was expecting that only the rules I specify will be used.

### Steps To Reproduce:

Here's my `pint.json`:

```
{
       "rules": {
            "visibility_required": true,
       }
}
```

My expectation is that it will only apply the `visibility_required` rule alone and not any other preset or default rules. Which means that if my code is already following this rule then nothing else will be fixed. Turns out it's not, as things like `unused_imports` are still getting applied.

Or is specifying a preset and turning off some of it's rules the only way to do this? so there's really no way to specify just one or two rules.

```
{
    "preset": "laravel",
    "rules": {
        "simplified_null_return": true,
        "braces": false,
        "new_with_braces": {
            "anonymous_class": false,
            "named_class": false
        }
    }
}
```

**Comment by nunomaduro** [comment]
It's not possible to specify a single rule. And yes, by doing `"visibility_required": true,` you are simply overriding that rule, and the other rules will remain. As workaround, you may use PHP CS Fixer directly.
