### ISSUE TITLE
Make PSR-12 the default preset

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [laravel/pint#116]
I note that this project originally started with [PSR-12](https://www.php-fig.org/psr/psr-12/) as the default preset. This makes a lot of sense to me as PSR-12 is the industry recognised, collaboratively developed, modern code formatting standard for PHP.

The current "Laravel" preset is unknown and undocumented (outside of reading the preset configuration).

Futhermore, [according to Laravel's documentation](https://laravel.com/docs/9.x/contributions#coding-style), the Laravel framework itself adheres to PSR-2 (and asks all contributors to follow suit):

> Laravel follows the [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) coding standard

So why set a new undocumented coding style as the default in Laravel Pint?

The PHP community doesn't need another new standard: https://xkcd.com/927/

Thanks.

**Comment by nunomaduro** [comment]
We've no plans to change that.

**Comment by JohnnyWalkerDesign** [comment]
Can you at least explain what the Laravel preset is and how it relates to PSR-2 or PSR-12?
