### ISSUE TITLE
Removing imports from same namespace is not loading Eloquent relationships

### ISSUE THREAD

**Issue by thebazshah** [laravel/pint#118]
In current Laravel version (v9.19) I am having this issue. In my model classes, Pint removes imports from same namespace i.e. models imported from same namespace. And because of this the eloquent relationships are not loading even when I query my model using `with` clause. Here is the code I have written in my controller function.

```php
$item = Item::with([
    'grade' => function ($q) {
        $q->select('id', 'title', 'slug', 'description', 'org_search_key', 'isActive');
    },
    'subject' => function ($q) {
        $q->select('id', 'title', 'slug', 'description', 'org_search_key', 'isActive');
    },
])->where('id', $request->itemId)->first();
```

In the model class if I import `Grade` and `Subject` classes, these relationships work fine. If classes are not imported (i.e. removed by Pint), the relationships turn out to be `null`.

`laravel/framework: ^9.19`
`laravel/pint: ^1.0`

**Comment by driesvints** [comment]
> Pint removes imports from same namespace i.e. models imported from same namespace.

This is most likely a bug in your code as this is intentionally. If the code does not work without the imported models something is wrong with autoloading. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
