### ISSUE TITLE
Preset can't be overridden by rules list;

### ISSUE THREAD

**Issue by guiribmedeiros** [laravel/pint#124]
- Pint Version: v1.2.0
- PHP Version: v8.0.24

### Description:
- The `laravel` preset rules are not being overridden by the rules list;
- Other presets like `symfony` are allowing that;
- I believe that the last input rule should be the one to be used, so `rules` > `preset`;

### Steps To Reproduce:

- When the rules are present on `rules` property are present the preset's rules already, they won't work (or overridden);
- This is a guess;

```
{
    "preset": "laravel",
    "rules": {
        "concat_space": {
            "spacing": "one"
        }
    }
}
```

- But, when they are not present the preset's rules, they will work (or overridden);
- This is a guess;

```
{
    "preset": "symfony",
    "rules": {
        "concat_space": {
            "spacing": "one"
        }
    }
}
```

**Comment by guiribmedeiros** [comment]
Looking through the code, I found this logic on the `preset` method at `App\Factories\ConfigurationFactory` class:

```
return (new Config())
            ->setFinder($finder)
            ->setRules(array_merge($localConfiguration->rules(), $rules))
            ->setRiskyAllowed(true)
            ->setUsingCache(true)
            ->registerCustomFixers([
                // Laravel...
                new LaravelPhpdocOrderFixer(),
                new LaravelPhpdocSeparationFixer(),
                new LaravelPhpdocAlignmentFixer(),
            ]);
```

And the `array_merge($localConfiguration->rules(), $rules)` logic on the `setRules` method is keeping the preset's rules over the received rules (through the configuration), so inverting the order of the parameters will fix the issue - tried to push a PR myself but I had no access 😅

**Comment by guiribmedeiros** [comment]
I've managed to send a PR: https://github.com/laravel/pint/pull/125 ✌️

**Comment by driesvints** [comment]
Looks like you already sent in a PR. Let's see what Nuno says.

**Comment by keizah7** [comment]
```json
{
    "preset": "laravel",
    "rules": {
        "concat_space": ["spacing"]
    }
}
```

```
In AbstractFixer.php line 152:
                                                                                                        
  [concat_space] Invalid configuration: The option "0" does not exist. Defined options are: "spacing".  
                                                                                                        

In OptionsResolver.php line 871:
                                                                  
  The option "0" does not exist. Defined options are: "spacing".  
      
```
