### ISSUE TITLE
Support Rules Options

### ISSUE THREAD

**Issue by julien-boudry** [laravel/pint#13]
Hi,

Can be great to support rules options in the config file.

Options example: https://mlocati.github.io/php-cs-fixer-configurator/#version:3.8|fixer:new_with_braces

**Comment by nunomaduro** [comment]
Can you check this? https://github.com/laravel/pint#rules.

**Comment by julien-boudry** [comment]
I see the rules support. But not the rules options support. No examples or mentions.

**Comment by julien-boudry** [comment]
Concrete example: I want to reverse [this rule](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.8|fixer:new_with_braces), which is supported by setting both options to false.
