### ISSUE TITLE
Pint uses LF line endings in Windows when git core.autocrlf=true

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/pint#134]
- Pint Version: 1.2.1
- PHP Version: 8.1.12

### Description:

We have developers who use windows in local environment, so we have `core.autocrlf=true` in git to preserve the `CRLF` on windows but commit with `LF`.

When running pint, it changes all the line endings from `CRLF` to `LF` causing hundreds of changed files in the source control, even when the content wasn't changed at all. 

I think the expected behaviors would be to preserve the line endings of the target OS. Or do you recomend us to switch to disable `core.autocrlf`?

### Steps To Reproduce:

1. Enable `core.autocrlf=true` if not already enabled: `git config --global core.autocrlf true`
2. Clone any laravel repository and `composer install`.
3. Run Laravel pint.

All the `CRLF` will be changed to `LF` causing hundreds of file changes.

**Comment by nunomaduro** [comment]
Since this is the first report about this situation, I would advise you to stick to what is suggested by Pint. If we start to receive more reports of people asking for this feature, we will reconsider it. Thank you for the detailed report.

**Comment by taylorotwell** [comment]
@nunomaduro does php-cs-fixer have a setting to leave CRLF alone?

**Comment by nunomaduro** [comment]
@taylorotwell Actually, found that there is an option to specify the `endingLine`.

@jhm-ciberman Do you mind of follow the following steps to see if this solution we have prepared works for you?

```
// Run this command in your application:
composer require laravel/pint:dev-feat/line-ending --dev
// Set the following options in your `pint.json`:
{
    "lineEnding": "\r\n"
}
// Run Pint again.
```

**Comment by jhm-ciberman** [comment]
Sorry the delay, we had a big rollover this week. It worked perfectly but I have some questions: 

If I checkout our repo from Unix and run pint from Unix this will cause the opposite (`LF` -> `CRLF`) causing thousands of file changes, am I right? 

At the moment I've said what you said in the beginning and stuck with `LF` for both Unix and Windows changing my `.gitattributes` file to:
```diff
- * text=auto
+ * text=auto eol=lf
*.css linguist-vendored
*.scss linguist-vendored
*.js linguist-vendored
CHANGELOG.md export-ignore
```
And configuring pint with the default of `LF`:
```json
{
    "preset": "laravel"
}
```

This makes git checkout with `LF` on both Unix and Windows and pint to use `LF` as newline both on Unix and Windows.

Do you recommend me this approach?

**Comment by driesvints** [comment]
We don't really know what to do here ourselves. Feel free to send in a PR if you can come up with something 👍

**Comment by driesvints** [comment]
We changed the default in the skeleton. I guess this can be closed now?

**Comment by jhm-ciberman** [comment]
Yes, sure! Thank you!
