### ISSUE TITLE
Use PHP-CS-Fixer 3.14.x instead of 3.13.1

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/pint#142]
This version has much expected fixes to `binary_operator_spaces` and improved handling of PHPDoc for `\Closure`
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.14.0

**Comment by driesvints** [comment]
Thanks, I've sent in a PR to bump it: https://github.com/laravel/pint/pull/143
