### ISSUE TITLE
Memory exhausted

### ISSUE THREAD

**Issue by sfilzek** [laravel/pint#144]
- Pint Version: 1.4.1
- PHP Version: 8.1.0
- OS: Windows 11

### Description:
Pint runs and then fails with a memory exhausted error:

```
.\vendor\bin\pint
  ............................................................................................................................................
  ............................................................................................................................................
  ...................................................................
In Tokens.php line 987:

  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes)
```

Is there any way to figure out which file it is on when it hits this error?

**Comment by nunomaduro** [comment]
It's hard to say the specific file. However, can you try to increase the PHP CLI memory to a couple of GB?

**Comment by sfilzek** [comment]
I increased the memory limit to 1024M in php.ini and that fixed it, thanks!

```
memory_limit = 1024M
```
