### ISSUE TITLE
Support for external config file

### ISSUE THREAD

**Issue by apsg** [laravel/pint#145]
It would be great to be able to provide url for external config json file for PINT. 
In all of my projects I use the same coding standards. It would be great to create a repo for my rules and then just provide pint with an url to those rules, instead of copy-pasting it every single time. 
Bonus - in this scenario, if I decide to update my coding rules, I need to do it only once, and all my projects can used modified version right away.

**Comment by driesvints** [comment]
Right now a url isn't possible but you can specify a path. Suggestion: create a composer package with your company rules and include that in your project so you can reference it as documented here: https://laravel.com/docs/9.x/pint#configuring-pint
