### ISSUE TITLE
no_superfluous_phpdoc_tags rule is not removing tags of classes in the same namespace

### ISSUE THREAD

**Issue by joostdebruijn** [laravel/pint#147]
- Pint Version: 1.5.0
- PHP Version: 8.2.2

### Description:
It seems that the new no_superfluous_phpdoc_tags rule is not removing fully qualified tags of classes that are in the same namespace.

### Steps To Reproduce:
**app/Models/User.php**
```php

<?php

namespace App\Models;

class User extends Model
{
    //
}
```

**app/Models/Group.php**
```php

<?php

namespace App\Models;

class Group extends Model
{
    /**
     * @param \App\Models\User $user
     */
    public function addUser(User $user) {
        //
    }
}
```
In this case I expect that `@param \App\Models\User` will be removed, but it isn't.

**Comment by driesvints** [comment]
Hi there, we only implement the rule of PHP CS Fixer. Please open an issue with them if you think there's an issue. Thanks
