### ISSUE TITLE
no_superfluous_phpdoc_tags rule doesn't remove tags with PHP 8 Attributes

### ISSUE THREAD

**Issue by EriBloo** [laravel/pint#148]
- Pint Version: 1.5
- PHP Version: 8.2

### Description:
When Attribute is added to parameter it is not removed from phpdoc even when it could've been. I'm not sure if this is intended behaviour.

### Steps To Reproduce:
Before formatting:
```php
    /**
     * @param string $uuid
     * @param CreateData $data
     */
    public function __construct(
        #[AggregateUuid]
        public string     $uuid,
        public CreateData $data
    )
    {
    }
```
After formatting:
```php
    /**
     * @param  string  $uuid
     */
    public function __construct(
        #[AggregateUuid]
        public string $uuid,
        public CreateData $data
    ) {
    }
```

(in addition this example will leave phpstorm reporting `PHPDoc comment signature is not complete`)

**Comment by driesvints** [comment]
Hi there, we only implement the rule of PHP CS Fixer. Please open an issue with them if you think there's an issue. Thanks
