### ISSUE TITLE
Add support for PER : PHP Evolving Recommendation

### ISSUE THREAD

**Issue by jdecode** [laravel/pint#153]
Add support for PER : PHP Evolving Recommendation

https://github.com/php-fig/per-coding-style
https://github.com/php-fig/per-coding-style/blob/master/meta.md

Since v1 of PER is an exact replica of PSR-12, so adding support of the flag `--per` and using the `psr12` as the underlying style guide might be a good point to start.

Expectation from PER is to go a gradual change in the guide as per the evolving nature of the language (more like "semvar", rather than following the PSR-1, PSR-2, PSR-12 changes - which take quite long to approve and adopt).

Even if no changes are done/approved as part of this issue, the idea is to highlight the ongoing changes so that efforts can start moving in this direction.

**Comment by driesvints** [comment]
Thanks but Pint really is focused at the Laravel preferred coding style so we're not looking into adding support for other presets sorry.

**Comment by jdecode** [comment]
PSR-12 standards would be replaced by PER (currently in progress).

Since we are currently supporting PSR-12, and I am assuming/hoping that PHP standards will always be supported (despite the focus on Laravel standards), so switching over to supporting PER would be something that we would have to do in near future, hence the recommendation.
