### ISSUE TITLE
Add support for GLOB patterns to exclude option

### ISSUE THREAD

**Issue by brdv** [laravel/pint#156]
Hi All,

I've been trying to migrate our old setup to pint, but having some issues with excluding specific files.

## Problem
Let's say I have these files:
path/to/folderToExclude/index.php
path/to/folderToExclude/helper.php
path/to/folderToExclude/db.php

With the following exclude block (including glob), I'd expect all files to be excluded from pint:

// snippet from pint.json in root of project
"exclude": [
        "**/folderToExclude/**"
    ],
When I run pint, however, it runs over all of the files listed above. I've tried a couple of variations and only the following seems to work (with exact path to a folder):

// snippet from pint.json in root of project
"exclude": [
        "path/to/folderToExclude/"
    ],

## Question
Could you please add support for GLOB patterns in the settings for pint?

**Comment by driesvints** [comment]
Hey there. Right now we don't have plans for this ourselves. You can attempt a PR if you like 👍

**Comment by brdv** [comment]
Thanks for your quick reply. May take a look at it when I have the time.
