### ISSUE TITLE
Support for formatter mode

### ISSUE THREAD

**Issue by bilogic** [laravel/pint#162]
Hi,

> All specified commands are expected to read in unformatted code on their stdin and print the formatted code to their stdout.
> In all cases, if any text is printed to stderr, the error will be relayed to the "Custom Format" output panel.
> If text is printed to stdout, error or no error, the file will be overwritten with the printed text.
> If there is no content written to stdout, error or no error, the formatting of the file will be skipped.

I quoted the above from https://github.com/Vehmloewff/custom-format

1. Read from STDIN
2. If formatted successfully, print formatted file to STDOUT and nothing to STDERR
3. If unable to format, print nothing to STDOUT, error/exception to STDERR and return non-zero

Can pint support an extra mode like this? 

Thank you.

**Comment by driesvints** [comment]
Thanks. Right now we have no plans for this, sorry.

**Comment by bilogic** [comment]
What about a PR?

**Comment by serbanrobu** [comment]
I also needed this function, but faked it with a script.
Maybe it's useful for someone:

```sh
file="$(mktemp --tmpdir=/dev/shm)"
cat - >"$file"
vendor/bin/pint --quiet "$file"
cat "$file"
rm "$file"
```

**Comment by gabrielbidula** [comment]
I have been using [Zed](zed.dev) editor and to make Pint work as a formatter I created the script: https://gist.github.com/gabrielbidula/4b8f84a02dafd242b0e1cf1d682fcaac
