### ISSUE TITLE
`--dirty` doesn't work with sail

### ISSUE THREAD

**Issue by maskeynihal** [laravel/pint#169]
### Pint Version

1.8.0

### PHP Version

8.2.4

### Description

**Running [pint](https://laravel.com/docs/10.x/pint#running-pint) from the sail and using `--dirty` doesn't work.**

It seems that the `--dirty` flag depends upon the output of git command `git status --short **.php` as seen [here](https://github.com/laravel/pint/blob/e033004fec425aa5473e6ffe6a23391236abb6e0/app/Repositories/GitPathsRepository.php#L34). Since the container is not a git repo, the `git status` command doesn't produce a list of modified files, and as a result, Pint doesn't fix any files. 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/26411488/230889020-a260de10-243e-4172-9313-f68d44dfa20b.png">

**0 files fixed**
<img width="698" alt="image" src="https://user-images.githubusercontent.com/26411488/230889145-f120cb18-1abf-42d2-bcc5-b3d7f4159140.png">

### Steps To Reproduce

- Make changes in one of the files that will be fixed by the pint
- Run the command
  ```bash
  ./vendor/bin/sail pint --dirty
  ```
- Doesn't fix any files

---
- Now run the command
  ```bash
  ./vendor/bin/sail pint
  ```
- Fixes the files

**Comment by maskeynihal** [comment]
Possible fixes might be: 

1. copy `.git` folder to the container, but might have issues in mono repos.
2. Modify [sail command](https://github.com/laravel/sail/blob/5edd50fe0f0c35faf9ddf074fd4f7ea7505cdb55/bin/sail#L310-L313) to check if the --dirty flag is passed as an argument. If so, run `git status --short **.php` command to generate a list of modified files and pass that list to Pint for fixing. However, this would require respecting the configuration file of Pint to ensure that only the files that need fixing are modified.

**Comment by nunomaduro** [comment]
At the moment, we rely on the git repository to obtain a list of "dirty" files, so I am afraid this is a current limitation of this feature.

**Comment by maskeynihal** [comment]
@nunomaduro , Yes and the reason for create this [PR](https://github.com/laravel/sail/pull/572) is to overcome this limitation. Would you mind checking it out?
