### ISSUE TITLE
Allow to format only specific files

### ISSUE THREAD

**Issue by zaalbarxx** [laravel/pint#17]
I believe it is an important feature to allow for passing list of files which should be formatted upon run instead of formatting all files. This is usable in case formatting is happening on pre-commit hook (for example in our case we have `lint-staged` configured which is formatting staged PHP files before commit). I don't see this anywhere as a documented feature and the command input arguments also does not seem to allow for this.

**Comment by d8vjork** [comment]
Yes! Any chance to get this done? I can help with this on a PR if you guys want.

I need this for a VSCode extension I'm working on

**Comment by jbrooksuk** [comment]
You can now fix a single file with `pint file.php` https://github.com/laravel/pint/commit/97df85a30ec3b794efe027219cf0736455f714a8

**Comment by zaalbarxx** [comment]
Does it allow to pass multiple files like `pint file1.php file2.php file3.php` ? This is how CS-Fixer works.

**Comment by jbrooksuk** [comment]
No, only one file at a time. 

Ping @nunomaduro.

**Comment by zaalbarxx** [comment]
@nunomaduro :) could we re-implement this to allow for multiple files ? I think it should be pretty straightforward.

**Comment by brandonburkett** [comment]
I would also really like this feature, using with lint-staged specifically.

**Comment by jbrooksuk** [comment]
You can do this now.
