### ISSUE TITLE
feat: multiple configuration files

### ISSUE THREAD

**Issue by TorstenDittmann** [laravel/pint#174]
In an organization we can be using a global configuration for pint and use it as a composer dependency and we would be using it like this:

```sh
pint --config vendor/my-company/coding-style/pint.json
```

Now some repositories where this is consumed, might need to add configuration on top, like `exclude`, `notPath` or `notName`.

Scenario:
- Have a global configuration file with some rules.
- Consume it via composer in multiple repositories
- Needing to exclude some paths relevant to some repositories on top of the global configuration

I can see 2 approaches on how to solve it:

1. `pint.json` can take a file path in `preset` or add a new `extends` value. Downside is, this could lead into a recursion hell and therefore also with a more complex implementation.
2. Allow passing multiple `--config xxx.json` arguments and merge the configurations by order. Like `pint --config vendor/my-company/coding-style/pint.json --config pint.json`.

I wouldn't mind working on this feature and can provide a PR 👍🏻 

PS: Created a draft PR for the second approach at #175.

**Comment by nunomaduro** [comment]
Thank you for submitting this feature proposal for Pint. Unfortunately, at this time, we do not have plans to add this feature to Pint.

**Comment by TorstenDittmann** [comment]
> Thank you for submitting this feature proposal for Pint. Unfortunately, at this time, we do not have plans to add this feature to Pint.

What would be the recommended steps to achieve this use-case? 🙂

This kinda blocks us from implementing such a global ruleset to our ~100 PHP repositories 👍🏻

**Comment by SanderMuller** [comment]
> Thank you for submitting this feature proposal for Pint. Unfortunately, at this time, we do not have plans to add this feature to Pint.

Would you be open for someone to create a PR for this? Our org would want to create our own preset which we want to use in our packages
