### ISSUE TITLE
Pint does not complete

### ISSUE THREAD

**Issue by rabol** [laravel/pint#179]
### Pint Version

1.9.0

### PHP Version

8.1.7

### Description

Pint starts, scans some files and then stop

```
  ..................................✓..................%    
  ```

No error nothing, it haas been working for a long time but 3 days ago it simply stopped.
It's if it want to print something and then dies

### Steps To Reproduce

I simply have it installed

**Comment by driftingly** [comment]
Can you try running it with the `-vvv` flag for verbose output:
```bash
vendor/bin/pint -vvv 
```

**Comment by rabol** [comment]
Here is the output:
```
Box Requirements Checker
========================

> Using PHP 8.1.17
> PHP is using the following php.ini file:
  /opt/homebrew/etc/php/8.1/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^8.1.0" or greater.
  ✔ The application requires the extension "zlib".
  ✔ The application requires the extension "json".
  ✔ The application requires the extension "mbstring".
  ✔ The application requires the extension "tokenizer".
  ✔ The application requires the extension "xml".
  
                                                                                                                                                                                                                                                                                                                   
 [OK] Your system is ready to run the application.                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                   


  .....................................................%                
```

**Comment by driesvints** [comment]
We'll need a repo to reproduce this. Can you provide us one with 

```bash
laravel new bug-report --github="--public"
```

**Comment by rabol** [comment]
That will generate a repo of my current project, correct?
I cannot do that as it dependencies to payed and private repo

**Comment by driesvints** [comment]
Sure 👍

**Comment by rabol** [comment]
Any chance that there is a 'logging' options that say which file pint is working on ?

**Comment by rabol** [comment]
I just tried ./vendor/bin/pint app and that works fine, but pint without anything stops

**Comment by rabol** [comment]
I have found the problem 

I have used a package orangehill/iseed to generate seeder for some of my very large tables, Country, State, City, one of the seeders, CitiesTableSeeder is very very big ~63Mb.
If I move that file, then pint is working again.

**Comment by driesvints** [comment]
I'm afraid that's not a realistic scenario we can account for, sorry. That's just a much too large file. It's probably best that you split that into different ones or use a database storage.

**Comment by aliwesome** [comment]
@driesvints I have the same issue using it.

**Comment by mshamaseen** [comment]
I had the same issue. I used `du -h *` inside the project directory to show sizes. It turned out that I have a seeder file that is almost 7MB, and it was taking a lot of time to complete.
