### ISSUE TITLE
Laravel/Pint installation error

### ISSUE THREAD

**Issue by patooz** [laravel/pint#181]
### Pint Version

1.10.0

### PHP Version

8.1.2

### Description

Cannot install Laravel/Pint while installing new Laravel v10.x app. It takes long and, in the end, it exceeded the timeout of 300 seconds.
I am using Ubuntu 22.04.2 LTS WSL.
![Capture6](https://user-images.githubusercontent.com/32126117/235299006-f8e8fabc-d82d-4df6-bc3f-d2e7be980709.PNG)

Attached is the screenshot.

### Steps To Reproduce

composer create-project laravel/laravel example-app

**Comment by DvDty** [comment]
Doesn't seem like an issue with the package.
Maybe try increasing the time: https://stackoverflow.com/a/25343207/3730982

**Comment by patooz** [comment]
used `--prefer-dist --no-dev` while installing laravel worked for me. Thanks @DvDty
