### ISSUE TITLE
[bug] php-cs-fixer 3.17 rule not working

### ISSUE THREAD

**Issue by sneycampos** [laravel/pint#186]
### Pint Version

1.10.1

### PHP Version

8.1.0

### Description

I'm trying to use "single_line_empty_body" fixer that was released in friendsofsymfony/php-cs-fixer 3.17.0 but not works.

pint.json 
```json
{
    "preset": "psr12",
    "rules": {
        "single_line_empty_body": true
    }
}
```

error
![image](https://github.com/laravel/pint/assets/585263/5cf15631-0738-4dc2-9470-f5dad1f76788)

### Steps To Reproduce

- use latest pint release 
- add `single_line_empty_body: true` to pint.json rules key
- run pint

**Comment by driesvints** [comment]
Sorry, I forgot to push the changes. Released now as v1.10.2
