### ISSUE TITLE
error with latest laravel 10 and pint 1.10.3 version

### ISSUE THREAD

**Issue by ArthurMelikyan** [laravel/pint#189]
### Pint Version

1.10.3

### PHP Version

8.1

### Description

Hello, I have one project where I used pint normally. After upgrading laravel  (10) and its dependencies it stopped working. 
I have installed fresh laravel to check if it comes from my project and run `./vendor/bin/pint --test -v ` or just `./vendor/bin/pint` command and it threw an error as well... so the error comes from pint itself

i tried different presets but the same error `unclosed '(' in on line 1) ` appears. 
Also, I have checked different versions of pint and downgraded to 1.4.0 and it worked... but higher versions throw the same error  

### Steps To Reproduce

install fresh laravel project
`laravel new laravel`
and then run `./vendor/bin/pint --test` command

```
  ..................................................PHP ParseError:  Unclosed '(' in  on line 1
PHP Stack trace:
PHP   1. {main}() /var/www/laravel-pint/vendor/bin/pint:0
PHP   2. include() /var/www/laravel-pint/vendor/bin/pint:117
PHP   3. require() /var/www/laravel-pint/vendor/laravel/pint/builds/pint:14
```

**Comment by Jubeki** [comment]
On macOS it is working on a fresh laravel installation.

Which operating system are you using?

**Comment by driesvints** [comment]
Feel free to create a new issue with the answers to the above questions from @Jubeki. Thanks
