### ISSUE TITLE
Keep a repository of pint rules

### ISSUE THREAD

**Issue by cosmastech** [laravel/pint#199]
It is incredibly inconvenient to have pint as part of our pipeline when the pint rules change drastically in minor versions.  In a project with 500 files, we have 54 files that need updated on a minor release (changing `?int` to `int|null` everywhere).  Our pipeline runs in such a way that the merge request fails when style isn't met rather than just auto-linting.

For a large scale enterprise application, it's not feasible or desirable to make all outstanding MRs require a rebase when pint is updated. It also makes the git history very messy.

While it's possible to just pin the current version of pint in both our composer.json and our pipeline, it's also not desirable to keep a potentially outdated version of a library just because the strongly opinionated rules change on a monthly basis.

It would be great if there was a repository of pint rules, and we could just say "use pint rules versions 1.0.8" and still benefit from security/performance updates that come down the pike in new versions.

**Comment by ToothlessRebel** [comment]
Maybe the solution for this is a command for Pint to publish the current ruleset to the project's `pint.json` configuration. Perhaps instead to version the presets such that `"presets": "laravel"` is an alias for `"presets: "laravel-10"` but a different preset can be selected?

**Comment by driesvints** [comment]
Hi @cosmastech. It's very much intended for this to happen. Pint is our opinionated code style formatter with preferred code styling conventions. If you use the library you can totally expect Pint to modify vast amount of files to new rules when they're added in minor versions. We do not consider these to be breaking. If you don't want this to happen then Pint might not be for you, sorry. Right now we have no plans to change this behavior.

**Comment by cosmastech** [comment]
> Hi @cosmastech. It's very much intended for this to happen. Pint is our opinionated code style formatter with preferred code styling conventions. If you use the library you can totally expect Pint to modify vast amount of files to new rules when they're added in minor versions. We do not consider these to be breaking. If you don't want this to happen then Pint might not be for you, sorry. Right now we have no plans to change this behavior.

It's not a problem of pint being opinionated. It's a problem of it making drastic changes on a minor version. 🤷

**Comment by driesvints** [comment]
@cosmastech I'm sorry we disagree on that.

**Comment by cosmastech** [comment]
> @cosmastech I'm sorry we disagree on that.

No hard feelings! I think we have a way around it for now.

I may make a PR or package to "freeze" a pint config in a state so that we can use this library without worrying about changes that disrupt the development flow.
