### ISSUE TITLE
Enum cases should not be altered

### ISSUE THREAD

**Issue by Procionegobbo** [laravel/pint#20]
- Pint Version: 0.1.5
- PHP Version: 8.1.1

### Description:
Enum cases should not be reformatted even regardless of keyword name.

Enum class: app/Enum/SegmentCastMissingAs.php
```php
namespace App\Enum;

enum SegmentCastMissingAs: string
{
    case NULL = 'null';
    case FALSE = 'false';
    case TRUE = 'true';
    case EMPTY_STRING = 'empty_string';
    case ZERO = 'zero';
    case IGNORE = 'ignore';
}
```

Pint change this style using Laravel preset:
```diff
-case NULL = 'null';
-case FALSE = 'false';
-case TRUE = 'true';
+case null = 'null';
+case false = 'false';
+case true = 'true';
case EMPTY_STRING = 'empty_string';
case ZERO = 'zero';
case IGNORE = 'ignore';
```

### Steps To Reproduce:
1. create class  `app/Enum/SegmentCastMissingAs.php`
2. Run `/vendor/bin/pint --preset laravel app/Enum/SegmentCastMissingAs.php`

**Comment by driesvints** [comment]
I think these are reserved constants and should not be used as ENUM values: https://www.php.net/manual/en/reserved.constants.php ?

**Comment by Procionegobbo** [comment]
Partially true: you cannot declare a constant with those names but nothing prevents you from using as an Enum case.

**Comment by claudiodekker** [comment]
Probably caused by https://cs.symfony.com/doc/rules/casing/native_function_type_declaration_casing.html (#10)

Unfortunately you can't exclude this just for enum cases by default, as this is an enable-or-disable kind of rule. 

Furthermore, as @driesvints mentioned you probably shouldn't be 'working around' reserved constants anyway. Just because the language doesn't cover it or block you from doing so, doesn't necessarily mean it's a good idea either. 

In either case, if you're _really_ eager to disable this, you _can_ [manually disable the rule](https://github.com/laravel/pint#rules) in a `pint.json` config file:
```json
{
    "rules": {
        "native_function_type_declaration_casing": false
    }
}
```

**Comment by driesvints** [comment]
I feel @claudiodekker is right. This is going to be an edge case at best.

**Comment by claudiodekker** [comment]
Alternatively, a custom rule _could_ be considered to still allow it _just_ for `Enum` cases, but I don't think I'm the right person to judge as to how such a fixer would look, and whether from a theoretical point of view it's actually a good idea to support this it anyway.

**Comment by Procionegobbo** [comment]
> Just because the language doesn't cover it or block you from doing so, doesn't necessarily mean it's a good idea either.

I agree that this could be an edge case but the language does not simply not blocking this case but allowing it. 
There is no such limitation on Enum cases (and  class constants if I'm not wrong) naming and Feel that the changes made in the example class  are not consistent with PHP syntax.
Maybe this is relevant #https://github.com/sebastianbergmann/phpunit/issues/4813

I don't feel comfortable disabling the rule because it's useful for numerous other case but I'll add to pint.json for now.

**Comment by jtomek** [comment]
Hello. I just ran into this too. I have an application that heavily relies on tables and related logic. My use case is to cast columns into Enums and group column-related helpers there, such as header(), default(), validators(), etc.

Solution: I changed case True and case False to case Yes and case No. :)
