### ISSUE TITLE
Shared rules across organisation

### ISSUE THREAD

**Issue by Jamesking56** [laravel/pint#21]
Hi,

I have a GitHub Org that has many Laravel apps. We currently have our own private coding standards repository which applies the same PHP CS Fixer rules across the organisation.

Is this same thing possible with Pint? We'd love to switch this over to use Pint but we don't really want to have to replicate the ruleset across all the applications, we'd rather this existed in a one centralised place across the whole organisation.

Cheers.

**Comment by Jamesking56** [comment]
Thanks for the speedy reply @driesvints 

I'm a bit confused though as #26 talks about custom fixers whereas I'm talking about shared configuration (using PHP CS Fixer's own fixers)?

**Comment by lukeraymonddowning** [comment]
If think you can use the `--config` option to point to a `pint.json` file in a vendor directory.

```bash
vendor/bin/pint --config=vendor/org/style/pint.json
```

**Comment by Jamesking56** [comment]
That makes more sense to me, a json file from vendor :+1:

**Comment by driesvints** [comment]
Yeah that's what I meant, sorry 😅

**Comment by Jamesking56** [comment]
No probs thanks for the speedy responses :+1:
