### ISSUE TITLE
Choose once for all which rules to include

### ISSUE THREAD

**Issue by lazer-hybiz** [laravel/pint#212]
I'm using the default laravel preset for multiple projects and almost every time I run `composer update` for minor releases there are new rules to the preset which in turn makes changes to some files.

I wouldn't call this a breaking change (although it can be - in `risky` rules e.g. [ordered_traits](https://cs.symfony.com/doc/rules/class_notation/ordered_traits.html#using-this-rule-is-risky) ) but its extremely annoying. I suggest the team sit down and discuss each available rule whether/how it should be implemented into the preset.

**Comment by crynobone** [comment]
You can lock pint to specific version if you want to avoid this, and only bump version every few months.

**Comment by lazer-hybiz** [comment]
@crynobone almost every PR is just adding a rule, why not decide once for all which rule to add?

**Comment by driesvints** [comment]
@lazer-hybiz this is exactly the point of this repo. That whenever you update the package you are adopting the current rule set of Laravel. Keeping your code up to date with what we enforce is what this package was intended for. If that’s annoying for you then maybe Pint isn’t for you, sorry.

**Comment by lazer-hybiz** [comment]
@driesvints but why not set the rule set of Laravel once for all? why do we need every week a new PR to add a rule?

**Comment by driesvints** [comment]
Because opinions change over time or PHP CS Fixer might come out with rules that'll help us fix styling to our own preferences more.
