### ISSUE TITLE
Inline comments of import lines doesn't move accordingly

### ISSUE THREAD

**Issue by rez0sk** [laravel/pint#214]
### Pint Version

1.12.0

### PHP Version

8.2.8

### Description

If you write inline comments in front of an import line, it doesn't move when pint tries to sort the imports and makes them irrelevant.

### Steps To Reproduce

For example, when you run pint on a file containing
```
use Illuminate\Database\Eloquent\Model;
use App\Models\User; //TODO something later
```
int turns into
```
use App\Models\User;
use Illuminate\Database\Eloquent\Model; //TODO something later
```

**Comment by nunomaduro** [comment]
This is something that could be improved on the `ordered_imports` rule of PHPCSFixer. Therefore, you can submit a pull request there.
