### ISSUE TITLE
Pint ignoring config file when processing single file

### ISSUE THREAD

**Issue by gilbitron** [laravel/pint#22]
- Pint Version: 0.1.5
- PHP Version: 8.1.5

### Description:

Pint seems to be ignoring my `pint.json` config when passing a file path.

<img width="1260" alt="CleanShot 2022-06-23 at 11 51 50@2x" src="https://user-images.githubusercontent.com/203882/175282792-51bca365-15a4-4da8-a21c-80cbda7843bd.png">

<img width="1253" alt="CleanShot 2022-06-23 at 11 52 02@2x" src="https://user-images.githubusercontent.com/203882/175282804-66eb58d5-9e5e-4850-abd9-d20c72775a35.png">

### Steps To Reproduce:

Add a `pint.json` with the following content:

```json
{
    "preset": "laravel"
}
```

`./vendor/bin/pint app/example/file.php` - Laravel preset not applied
`./vendor/bin/pint --preset=laravel app/example/file.php` - Laravel preset applied

**Comment by nunomaduro** [comment]
Fixed on `v0.1.6`.
