### ISSUE TITLE
Deprecated rules

### ISSUE THREAD

**Issue by realodix** [laravel/pint#222]
php-cs-fixer v3.33.0

- Rule `compact_nullable_typehint` 
  https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/whitespace/compact_nullable_typehint.rst
- Rule `curly_braces_position`
  https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/curly_braces_position.rst
- Rule `native_function_type_declaration_casing`
  https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/casing/native_function_type_declaration_casing.rst
- Rule `no_unneeded_curly_braces`
  https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/control_structure/no_unneeded_curly_braces.rst

**Comment by driesvints** [comment]
Thanks. A PR was sent 👍
