### ISSUE TITLE
Pint Crashing When Formatting Files

### ISSUE THREAD

**Issue by stephaneb74** [laravel/pint#227]
### Pint Version

1.13.3

### PHP Version

8.2.11

### Description

Pint crashes when trying to fix a PHP file, no matter which file it is.

### Steps To Reproduce

Laravel 9.

Whenever I try to run:

`./vendor/bin/pint path/to/file.php`

I get these errors:

`
In AbstractFixer.php line 143:[class_attributes_separation] Invalid configuration: Unexpected element type, expected any of "const", "method", "property" , "trait_import" and "case", got "integer#0"`

`In ClassAttributesSeparationFixer.php line 200:Unexpected element type, expected any of "const", "method", "property", "trait_import" and "case", got "integer#0".`

**Comment by Jubeki** [comment]
Seems to work on a fresh Laravel 9 Application (should not be relevant):

```
composer create-project laravel/laravel:^9.0 pint-bug-227
cd pint-bug-227
vendor/bin/pint app/Providers/AppServiceProvider.php
```

Do you use a custom pint config?
Which operating system are you using?

**Comment by stephaneb74** [comment]
> Seems to work on a fresh Laravel 9 Application (should not be relevant):
> 
> ```
> composer create-project laravel/laravel:^9.0 pint-bug-227
> cd pint-bug-227
> vendor/bin/pint app/Providers/AppServiceProvider.php
> ```
> 
> Do you use a custom pint config? Which operating system are you using?

I'm running Ubuntu 22.04. This is my pint.json:

```
{
    "preset": "laravel",
    "rules": {
        "general_phpdoc_annotation_remove": false,
        "no_superfluous_phpdoc_tags": false,
        "phpdoc_param_order": true,
        "concat_space": {
            "spacing": "one"
        },
        "not_operator_with_successor_space": false,
        "phpdoc_separation": true,
        "yoda_style": false,
        "class_attributes_separation": {
            "elements": ["method"]
        }
    }
}
```

**Comment by Jubeki** [comment]
You have configured on of your rules wrongly.

It should be:
```json
{
    "preset": "laravel",
    "rules": {
        "class_attributes_separation": {
            "elements": {
                "method": "one"
            }
        }
    }
}
``

**Comment by Jubeki** [comment]
See the PHP-CS-Fixer Documentation: https://cs.symfony.com/doc/rules/class_notation/class_attributes_separation.html

**Comment by driesvints** [comment]
Please see the above.

Thanks @Jubeki
