### ISSUE TITLE
Weird bugs when having set binary_operator_spaces: align_single_space_minimal

### ISSUE THREAD

**Issue by CamilleScholtz** [laravel/pint#245]
### Pint Version

1.13.9

### PHP Version

8.2.14

### Description

This bug happens since 1.13.9, not in 1.13.8. When having the `binary_operator_spaces` set to `align_single_space_minimal` all kinds of paths and strings get destroyed by spaces in places where they should be, some example:

```php
'postal-code'  => ['required',  'regex:/^[0-9]{4} ?[a-zA-Z]{2}$/'],
// becomes
'postal-code'  => ['required',  'regex:/^[0-9]{4} ?[a- zA- Z]{2}$/'],
            
'edit'   => Pages\EditArticle::route('/{record}/edit'),
// becomes
'edit'   => Pages\EditArticle::route('/{record} /edit'),
```

The config:

```json
{
    "preset": "laravel",
    "rules": {
        "no_useless_else": true,
        "binary_operator_spaces": {
            "default": "align_single_space_minimal"
        }
    }
}
```

### Steps To Reproduce

Set the config file as shown above and run laravel pint.

**Comment by Jubeki** [comment]
Is already fixed, will probably be released on Tuesday.

**Comment by phh** [comment]
@Jubeki Any way to test this? I've updated to `dev-main` but it seems like it's still causing me issues.

**Comment by driesvints** [comment]
Thanks @Jubeki
