### ISSUE TITLE
Preset for WordPress

### ISSUE THREAD

**Issue by AbmSourav** [laravel/pint#247]
Add new preset for WordPress themes and plugins.

**Comment by driesvints** [comment]
Sorry but Pint is really meant as Laravel's official preset. We have no plans for other frameworks or CMS's

**Comment by AbmSourav** [comment]
@driesvints but Pint has support for Symfony, isn't it...

**Comment by driesvints** [comment]
Not intentionally no

**Comment by AbmSourav** [comment]
Intentionally... really... !! 
@driesvints please check `SummaryOutput` class for the available preset list and feel free to explore the package's code base.

**Comment by driesvints** [comment]
Hey there. I'm sorry, it indeed seems we list Symfony as a preset. But in the end we're still most focused on the Laravel preset and want to be mindful of what else we add. Pint isn't directly intended as a fixer tool for other codebases than Laravel and adding others might open the door for much more requests for framework X & Y. We're already often getting questions about adding more presets or for new configuration and don't want that to be the focus or increase our maintenance burden. I hope you can understand.
