### ISSUE TITLE
Pint fails when using new PHP 8.3 features

### ISSUE THREAD

**Issue by OMKE** [laravel/pint#248]
### Pint Version

1.13

### PHP Version

8.3

### Description

Pint fails when using new PHP 8.3 features like:

1. readonly class 
2. typed constants

### Steps To Reproduce

1. Add readonly before class
`readonly class FacebookAdAccountService implements IntegrationAdAccountService`
2. Add type to constant:
`const string VIEW_STORES = 'view stores';`

**Comment by driesvints** [comment]
readonly works for me, typed constants not. We'll get the dependencies updated for tomorrow's release but in this is mainly a PHP CS Fixer issue.
