### ISSUE TITLE
I can't create a Laravel project since Pint was upgraded to 1.14.0

### ISSUE THREAD

**Issue by aphoe** [laravel/pint#252]
### Pint Version

1.14.0

### PHP Version

8.2.13

### OS

Windows 10

### Description

Laravel project creation keeps breaking with the error message below since pint was updated from v1.13.11 to 1.14.0 about four hours ago

```
Failed to execute git clone --mirror -- https://ghp...HqG:x-oauth-basic@github.com/laravel/pint.git C:/Users/My
  _PC/AppData/Local/Composer/vcs/https---github.com-laravel-pint.git/

  Cloning into bare repository 'C:/Users/My_PC/AppData/Local/Composer/vcs/https---github.com-laravel-pint.git'...
  warning: git-credential-manager-core was renamed to git-credential-manager
  warning: see https://aka.ms/gcm/rename for more information
  error: RPC failed; curl 18 transfer closed with outstanding read data remaining
  error: 6397 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
```

### Steps To Reproduce

`laravel new project`

### Other OS

So, I tried to create a new Laravel project on my server with runs on Ubuntu 20, and it works fine

**Comment by crynobone** [comment]
You need to upgrade your GIT installation: https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/rename.md
