### ISSUE TITLE
Can't disable Laravel fixers.

### ISSUE THREAD

**Issue by stephan-v** [laravel/pint#253]
### Pint Version

1.14

### PHP Version

8.2.15

### Description

It seems I can no longer disable custom Laravel rules. After running Pint you will get a warning:

> The rules contain unknown fixers: "Laravel/laravel_phpdoc_alignment".

My current pint.json file:

```
{
    "preset": "laravel",
    "rules": {
        "not_operator_with_space": false,
        "not_operator_with_successor_space": false,
        "Laravel/laravel_phpdoc_alignment": false
    }
}

```

### Steps To Reproduce

Run Pint using this `pint.json` file:

```
{
    "preset": "laravel",
    "rules": {
        "not_operator_with_space": false,
        "not_operator_with_successor_space": false,
        "Laravel/laravel_phpdoc_alignment": false
    }
}
```

**Comment by Jubeki** [comment]
The custom Laravel fixer was replaced in version [v1.13.9](https://github.com/laravel/pint/releases/tag/v1.13.9)

To disable the rule you should use the following instead:

```json
{
    "preset": "laravel",
    "rules": {
        "not_operator_with_space": false,
        "not_operator_with_successor_space": false,
        "phpdoc_align": true
    }
}
```

Or completely disable "phpdoc_align" by setting it to false.

**Comment by driesvints** [comment]
Thanks @Jubeki
