### ISSUE TITLE
GitHub Issue "Documentation issue" button does not link to laravel/docs

### ISSUE THREAD

**Issue by Vectorial1024** [laravel/pint#254]
### Pint Version

N/A

### PHP Version

N/A

### Description

When creating a new GitHub issue in this repo, I noticed I could click on "documentation issue" to be sent to the documentation repo, which I later found out to be `laravel/docs`. However, at this moment, the button actually sent me back to this repo, and then this repo understandably did not contain any docs, and then I was confused.

Please update the link to point to `laravel/docs`, thanks!

### Steps To Reproduce

See description.

**Comment by driesvints** [comment]
Thanks for reporting. I fixed this now.
