### ISSUE TITLE
Format the files using stdio

### ISSUE THREAD

**Issue by TheBlckbird** [laravel/pint#262]
### Problem

Editors like Zed use standard input output for formatting. This means that they write the contents of the current file to stdin and replace the file on disk with whatever is written to stdout. This means that it currently just puts the default output from pint into the file.

### Possible Solution

There should be an argument to pint that enables this behavior.  
Example: `pint --stdio`

I’m using version `v1.14.0`

Thank you for making and maintaining this and other projects!

**Comment by nunomaduro** [comment]
It seems like a feature request rather than an issue. Feel free to submit a pull request on this; we will consider it.

**Comment by TheBlckbird** [comment]
@nunomaduro Oh, so you’re not supposed to submit Feature Request but rather PRs directly? If so, you probably should remove the issue template "Feature Request".

I might look into implementing this

**Comment by nunomaduro** [comment]
Apologize! Be sure to first analyze if is a lot of code. I think Taylor would be willing to merge only if is a few lines of code.

**Comment by TheBlckbird** [comment]
Sorry, I’m not a native English speaker. This sentence is confusing me a bit. Is this what you meant?

- I should "think" about whether this is a lot of code
- Taylor probably won’t merge the PR if it is

Did I understand it right?
