### ISSUE TITLE
More extensive exlusion/inclusion rules 

### ISSUE THREAD

**Issue by samlinck** [laravel/pint#268]
In my project, we maintain a plugin folder containing various packages, some of which are installed via composer while others are not. We need to exclude the composer packages from laravel/pint, but not the others. Currently, our only option is to explicitly ignore all composer-installed plugins. It would greatly simplify  things if we could selectively unignore specific plugins, similar to how it's done in a .gitignore file.

**Comment by driesvints** [comment]
Thanks but right now we don't have plans for this sorry. You're always free to attempt a PR so we can look at some code.
