### ISSUE TITLE
Add pronunciation to documentation

### ISSUE THREAD

**Issue by octoxan** [laravel/pint#269]
There's a common disagreement amongst Laravel developers on whether it's pronounced "pint" like the glass featured in the logo, or whether it's pronounced like "lint" from being a PHP linter.

If Laravel Pint is so opinionated, stick the correct pronunciation somewhere in the README to end the debate once and for all.

**Comment by driesvints** [comment]
Err, not sure if that's needed tbh. Feel free to attempt a PR if you like.

**Comment by octoxan** [comment]
@driesvints with the pronunciation as in Pint like the glass of beer? Or do you pronounce it like lint with a p?

**Comment by nunomaduro** [comment]
Pint like the beer.
