### ISSUE TITLE
Pint with  --repair option does not exit but shows success instead

### ISSUE THREAD

**Issue by Tamas-hi** [laravel/pint#288]
### Pint Version

1.17.0

### PHP Version

8.2.2

### Description

According to the [docs ](https://laravel.com/docs/11.x/pint#running-pint): 

_If you would like Pint to fix any files with code style errors but also exit with a non-zero exit code if any errors were fixed, you may use the --repair option:_

`./vendor/bin/pint --repair`

However after creating a project with Laravel Breeze, this is the behavior I experience:

1. --test correctly signals a formatting error and exits

./vendor/bin/pint --test

  FAIL   .............................................................................................................................................. 46 files, 1 style issue  
  ⨯ routes/auth.php 

2. --repair correctly signals the formatting error, fixes it, but does not exist and returns with success:

./vendor/bin/pint --repair

  FIXED   ....................................................................................................................................... 46 files, 1 style issue fixed  
  ✓ routes/auth.php 

I think I should see a big red X in the last row instead of the green tick.

### Steps To Reproduce

1. Initialize a brand new laravel project with Laravel Breeze
2. Run Laravel Pint with the option --repair.

**Comment by nunomaduro** [comment]
@Tamas-hi can you try to understand why please? thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
