### ISSUE TITLE
What's the advantage over PHP-CS-Fixer

### ISSUE THREAD

**Issue by ibes** [laravel/pint#29]
Could there be two sentences about why to use Pint over PHP-CS-Fixer?

I imagine the output might be more enjoyable and I imagine the installation being easier. 

Is that correct? 
But likely pint could get old as it comes bundled with a PHP-CS-Fixer, right?

**Comment by driesvints** [comment]
Pint requires zero dependencies besides PHP ^8.0. It's compiled into a binary so you're never blocked from upgrading when newer PHP versions or dependencies of the dev requirements are released. It also provides a cleaner CLI output.

**Comment by BafS** [comment]
PHP-CS-Fixer is also available as a "no dependency" package (phar), you can find it with every release, for example last one: [php-cs-fixer.phar](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.8.0/php-cs-fixer.phar).

**Comment by wouterj** [comment]
...and is available as a shim package to install this phar as a Composer dependency just like Pint: https://packagist.org/packages/php-cs-fixer/shim

**Comment by driesvints** [comment]
> and is available as a shim package to install this phar as a Composer dependency just like Pint:

Didn't know about that one myself! Doesn't seem to be documented at https://cs.symfony.com/ ?

> Isn't the only benefit of Pint that it comes included with a Laravel CS ruleset? 

And better CLI output. Plus it indeed wraps both a nice short executable and has our preferred ruleset.

>  Something that might also become available outside Pint for PHP-CS-Fixer 

Yes of course but unsure when/if we'll work on that ourselves. Of course, Pint is open source and the preset is already available here: https://github.com/laravel/pint/blob/main/resources/presets/laravel.php

**Comment by wouterj** [comment]
> Didn't know about that one myself! Doesn't seem to be documented at https://cs.symfony.com/ ?

Oh indeed, I'll see if I can fix that. Thanks for the reply :)

**Comment by BafS** [comment]
> And better CLI output. Plus it indeed wraps both a nice short executable and has our preferred ruleset.

Why not backporting the output to the main repo? I think it would be valuable for all of us and it would avoid having a schism

Maybe the Laravel rulset could also be part of it? Doing so it would still be straitforward to use the Laravel ruleset for Laravel users

**Comment by driesvints** [comment]
Building a new package gives us the most flexibility to do the changes which we want to do. Of course, anyone can send in a PR to PHP CS Fixer with some of the changes/preset of this package if they want to 👍

**Comment by drupol** [comment]
> Building a new package gives us the most flexibility to do the changes which we want to do. Of course, anyone can send in a PR to PHP CS Fixer with some of the changes/preset of this package if they want to +1

That's the endless discussion. 

"Should I fork and do whatever I want in my new branded package?" or "Contribute back by understanding how it works and make it profitable for everyone?"

For sure, it surely gives more flexibility when nobody is there to review upstream PRs !

Nice state of mind. Well done.

Good luck guys.

**Comment by driesvints** [comment]
@drupol should we say the same about all of the packages/wrappers around our own first party packages? No, we're glad that people are enjoying them and are extending them in ways that work for them. That's a great mindset actually, if you can't merge something upstream, extend and build it yourself. The entire package ecosystem is built that way.

Also, you're entitled to your own opinion but you don't have to be snarky about it. We're all adults here.
