### ISSUE TITLE
Add "--print" option for formatter managers like dprint

### ISSUE THREAD

**Issue by adaliszk** [laravel/pint#293]
I have a fairly complex monorepo setup where we are migrating to PHP and Laravel. To accommodate all the different languages, we use [Dprint](https://dprint.dev) as the formatter tool so that all files would be properly maintained.

In order to use Pint with [Dprint](https://dprint.dev), we would need a simple print option where Pint would just print out the formatted result instead of writing to the disk back. With that, it would be possible to run https://github.com/dprint/dprint-plugin-exec, and parallelize the formatting needs as well as integrate with the rest of the ecosystem.

Would this be fine with you to add?

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. For these, we'd appreciate a pull request instead so we can look at actual code. If you need feedback about an idea, we suggest to [post an idea discussion here](https://github.com/laravel/framework/discussions/categories/ideas) first. Please only use the issue tracker to report bugs and issues with this library.

Thanks!

**Comment by adaliszk** [comment]
I see. Could you modify the GitHub template so it does not accept feature requests? Currently, it does allow it.
