### ISSUE TITLE
unable to install after laravel socialite

### ISSUE THREAD

**Issue by pakistanimoon** [laravel/pint#297]
### Pint Version

1.18.1

### PHP Version

8.4

### Description

i always receiving these issues

Install of laravel/pint failed

In Git.php line 471:

  Failed to execute git clone --no-checkout -- https://ghp...oAD:x-oauth-basic@github.com/laravel/pint.git E:\wamp64\
  www\unlock-data\backend\vendor\laravel\pint && cd /D E:\wamp64\www\unlock-data\backend\vendor\laravel\pint && git r
  emote add composer -- https://ghp...oAD:x-oauth-basic@github.com/laravel/pint.git && git fetch composer && git remo
  te set-url origin -- https://github.com/laravel/pint.git && git remote set-url composer -- https://github.com/larav
  el/pint.git

  Cloning into 'E:\wamp64\www\unlock-data\backend\vendor\laravel\pint'...
  error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
  error: 2819 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output
  
  
  --------------------------------------------------------------------------------
   Failed to execute git checkout 35c00c05ec43e6b46d295efc0f4386ceb30d50d9 -- && git reset --hard 35c00c05ec43e6b46d29
  5efc0f4386ceb30d50d9 --

  error: unable to read sha1 file of RELEASE.md (dc7619b764a90f4e9c528105544dbee4729f424f)
  error: unable to read sha1 file of builds/pint (7d5a166e48495c83a47f16a0ca06fe2803b578e5)
  error: unable to read sha1 file of config/app.php (c292f27da95c99f6d0b020c6c633937d81026f5e)
  error: invalid object 100755 7d5a166e48495c83a47f16a0ca06fe2803b578e5 for 'builds/pint'
  Note: switching to '35c00c05ec43e6b46d295efc0f4386ceb30d50d9'.

  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.

  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:

    git switch -c <new-branch-name>

  Or undo this operation with:

    git switch -

  Turn off this advice by setting config variable advice.detachedHead to false

  HEAD is now at 35c00c0 Merge branch 'main' of github.com:laravel/pint
  error: unable to read sha1 file of RELEASE.md (dc7619b764a90f4e9c528105544dbee4729f424f)
  error: unable to read sha1 file of builds/pint (7d5a166e48495c83a47f16a0ca06fe2803b578e5)
  error: unable to read sha1 file of config/app.php (c292f27da95c99f6d0b020c6c633937d81026f5e)
  fatal: Could not reset index file to revision '35c00c05ec43e6b46d295efc0f4386ceb30d50d9'.

  It looks like the commit hash is not available in the repository, maybe the tag was recreated? Run "composer update
   laravel/pint" to resolve this.
  

### Steps To Reproduce

composer require laravel/socialite in laravel 11

**Comment by crynobone** [comment]
Hey there,

While this may be a legitimate issue, can you first try posting your problem or question on one of the support channels below? If this issue can be definitively identified as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
