### ISSUE TITLE
Deprecated calls on the compiled pint executable with PHP 8.4.1

### ISSUE THREAD

**Issue by ricdizio** [laravel/pint#318]
### Pint Version

1.18.3

### PHP Version

8.4.1

### Description

I'm getting deprecated warning calls using latest pint version on my laravel project:
`
Deprecated: optional(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/support/helpers.php on line 190

Deprecated: with(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/support/helpers.php on line 430

Deprecated: Illuminate\Container\Container::beforeResolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/container/Container.php on line 1151

Deprecated: Illuminate\Container\Container::resolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/container/Container.php on line 1171

Deprecated: Illuminate\Container\Container::afterResolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/container/Container.php on line 1191

Deprecated: Illuminate\Container\Container::setInstance(): Implicitly marking parameter $container as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/container/Container.php on line 1430

Deprecated: Illuminate\Contracts\Container\Container::beforeResolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/contracts/Container/Container.php on line 200

Deprecated: Illuminate\Contracts\Container\Container::resolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/contracts/Container/Container.php on line 209

Deprecated: Illuminate\Contracts\Container\Container::afterResolving(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/contracts/Container/Container.php on line 218

Deprecated: Illuminate\Support\Traits\Conditionable::when(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/conditionable/Traits/Conditionable.php on line 21

Deprecated: Illuminate\Support\Traits\Conditionable::when(): Implicitly marking parameter $default as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/conditionable/Traits/Conditionable.php on line 21

Deprecated: Illuminate\Support\Traits\Conditionable::unless(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/conditionable/Traits/Conditionable.php on line 53

Deprecated: Illuminate\Support\Traits\Conditionable::unless(): Implicitly marking parameter $default as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/conditionable/Traits/Conditionable.php on line 53

Deprecated: Illuminate\Support\Arr::first(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/collections/Arr.php on line 188

Deprecated: Illuminate\Support\Arr::last(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/collections/Arr.php on line 219

Deprecated: Illuminate\Events\Dispatcher::__construct(): Implicitly marking parameter $container as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/ricdizio/laravel-test/src/vendor/laravel/pint/builds/pint/vendor/illuminate/events/Dispatcher.php on line 75
`

### Steps To Reproduce

1. Execute pint with latest php version

**Comment by crynobone** [comment]
This should be fixed on the latest release.
