### ISSUE TITLE
per directory pint.json parsing

### ISSUE THREAD

**Issue by fruitl00p** [laravel/pint#37]
This might be a bit farfetched but with all the mono-repo rage (and i.e. having a cross PHP version phar source in a larger project) one might want Pint to check everywhere but read the pint.json in the current working directory... 

This is alot like how .gitignore works when placing it into a subdirectory and such. This would allow bigger repositories to have multiple rulesets, rules or even presets between directories and still "only" have the single pint command to fix it all ;)

Thanks!

**Comment by driesvints** [comment]
I feel that this is currently a bit outside the project's scope, sorry. Right now, we consider Pint fixing code as a whole on the entire codebase in the same manner.

**Comment by fruitl00p** [comment]
Too bad, but understandable
