### ISSUE TITLE
Should not modify the string inside the explode function

### ISSUE THREAD

**Issue by zaidysf** [laravel/pint#38]
- Pint Version: 0.1.7
- PHP Version: 8.0

### Description:
Pint added spaces between | on explode function.
e.g from `explode('|', $string)` to `explode(' | ', $string)`
So, this will give app errors. Is it expected?

**Comment by driesvints** [comment]
Please provide a way to reproduce.

**Comment by jbrooksuk** [comment]
Using this test code:

```php
<?php

$string = 'laravel|team';
explode('|', $string);
```

I was not able to recreate this issue using any preset in Pint.
