### ISSUE TITLE
Add an inclusion list that overrides the exclusion list

### ISSUE THREAD

**Issue by edalzell** [laravel/pint#39]
When I'm working on a package, I composer symlink to the package's dev folder, so I can work in my laravel app on the package.

I have the VS Code extension installed and it ignores the `vendor` folder, but I actually want it to format my package code, which is in the app's `vendor` folder.

Perhaps an `include` config that allows us to add specific folders that might otherwise be excluded?

Thanks!

**Comment by driesvints** [comment]
I feel that this is a bit too much of an edge case and that you should install Pint directly on your package to do the formatting there. Sorry

**Comment by fylzero** [comment]
@driesvints My current company has a very complex application that is woven together by many packages developed directly in vendor (this wasn't my idea). I have been looking into code enforcement tools and would like to use Pint but this limitation means we would need to install Pint on 40+ packages and break out development to each one which would be a huge pain. This feature, though supporting a lesser used edge case, would add flexibility to Pint. I don't imagine this should be very difficult or heavy to implement. Can we please consider adding this? I can work on submitting a PR if you'd consider to add it in.

**Comment by fylzero** [comment]
@driesvints Nevermind! - took me about 30 minutes of code reading to learn you can specify the path as the arguement.

Just run "vendor/bin/pint vendor/whatever" and it will work! Nice!
