### ISSUE TITLE
Pint ignores annotations like "@formatter:off" and "phpcs:ignoreFile", but the exclusion will not ignore a specified file but only works on folders

### ISSUE THREAD

**Issue by SimonMacIntyre** [laravel/pint#4]
- Pint Version: 0.1.0
- PHP Version: 8.1

### Description:
I tried to manually exclude `_ide_helper.php`, but it seems exclusion only works on entire folders. Adjacent to that, the
existing annotation-comments to skip php-cs-fixer are not considered.

### Steps To Reproduce:
Try to exclude at root `_ide_helper.php`

**Comment by victor-falcon** [comment]
Maybe you should add `_ide_helper_modules.php` too?

**Comment by nunomaduro** [comment]
@victor-falcon Any other file that gets added by the ide helper package?

**Comment by malohtie** [comment]
@nunomaduro it would be nice if we can exclude files manually in pint.json not the entire folder

**Comment by victor-falcon** [comment]
> @victor-falcon Any other file that gets added by the ide helper package?

@nunomaduro Just those, as far I know
