### ISSUE TITLE
PHPStorm `laravel` IDE preset

### ISSUE THREAD

**Issue by michael-rubel** [laravel/pint#42]
Hi @nunomaduro 

We just moved the project to meet Pint coding standard with `laravel` preset.
Any chance we someday get the PHPStorm IDE config available with rules to meet this style?

**Comment by nunomaduro** [comment]
I've no idea. Sorry.

**Comment by tarreislam** [comment]
> michael

You could add a file watcher to fix on save, just like phpstorm does with "ESLINT"

You could also do it from WSL, check this

Check this out: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004625879-WSL-and-file-watchers

**Comment by michael-rubel** [comment]
@tarreislam of course I can, but:
1. That would be slow to run on every change.
1. PHPStorm built-in "Laravel" code style differs from that one in Pint.
1. The team already used to PHPStorm quick styling/docblocking.
