### ISSUE TITLE
Max line length

### ISSUE THREAD

**Issue by ChrisRiddell** [laravel/pint#46]
Hello,

Sorry about the title was not really sure what to call it, I'm not sure if this is within the scope of the Pint project but through Laravel long lines are broken up into multiple lines example from FormRequest

```php
return $factory->make(
            $this->validationData(), $this->container->call([$this, 'rules']),
            $this->messages(), $this->attributes()
        )->stopOnFirstFailure($this->stopOnFirstFailure);
```

Would be nice if pint was able to detect and "fix" long lines like the above.

**Comment by nunomaduro** [comment]
Thank you for the suggestion. We will consider it!

**Comment by esetnik** [comment]
@nunomaduro how do we use the max line length functionality?

**Comment by esetnik** [comment]
I think this should be reopened. I am not sure why it was closed.
