### ISSUE TITLE
Moving custom Laravel rules to upstream PHP CS Fixer

### ISSUE THREAD

**Issue by szepeviktor** [laravel/pint#47]
Hello! It would be great to send a PR to PHP CS Fixer with [the 3 Laravel rules](https://github.com/laravel/pint/tree/main/app/Fixers).

Who's is brave enough to do this copy-paste job?

**Comment by driesvints** [comment]
You? 😅

**Comment by szepeviktor** [comment]
Start: right now! 🐎
