### ISSUE TITLE
copyrights/license violation

### ISSUE THREAD

**Issue by keradus** [laravel/pint#50]
Hey.

I see we have yet another wrapper of https://github.com/FriendsOfPHP/PHP-CS-Fixer/ .
*I think it's totally fine* and I can only encourage you to consider to also contribute back to the main project, especially with the generic parts. We already made a lot of elements customizable via interfaces, and we could make more customizations for sure.

Same time, if you decide to COPY-PASTE the source file from PHP CS Fixer repo, please remember to keep respect the original ownership and license.

-----

The 3 rules were created by copy-pasting them from main repo and doing small adjustments, eg [LaravelPhpdocOrderFixer](https://github.com/laravel/pint/pull/3/files#diff-39a473f500c126459a9bf238381b42c7dbd7dfab1404d6df5078f3b0094461aaR13) is clone of [PhpdocOrderFixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Phpdoc/PhpdocOrderFixer.php) with slight adjustments to match your custom needs (most of logic, variable names, description etc is copy-pasted).

<details>
<summary>It was also admitted openly in the PR that was introducing those files</summary>
<img width="898" alt="Screenshot 2022-06-25 at 12 07 11" src="https://user-images.githubusercontent.com/2716794/175768957-1668b3a2-4c2a-4fc3-b01b-208c7b02fe8f.png">
</details>

-----

You are totally OK to do that as long as you keep the [copyrights](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Phpdoc/PhpdocOrderFixer.php#L5-L13) and [license](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/LICENSE). Please, let's have respect to one another work.
> (...) The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software. (...)

**Comment by driesvints** [comment]
Hi @keradus. You're quite right, thanks for pointing that out. I've gone ahead and added that copyright notice and the license directly to each of those files: https://github.com/laravel/pint/commit/f87868a136cb2238422baebb2d2bc212e257ffa0. Does that look good to you? Let me know if you'd like other adjustments here.

I'd also like to point out that we handle tons of PR's daily and it's simply not possible for us to check the origin of code or license/copyright requirements of every single code that is sent in. We rely on our PR authors to be sensible and mindful about this. Of course if anything arises that we missed we'll gladly follow up and make any necessary adjustments 👍 

In general we also want to very much thank you and the rest of PHP CS Fixer of all the work you did and are still doing. I realise there has been some friction with the recent release of Pint but if you want we're always happy to discuss what we can do better in the future. If we can give more credit to PHP CS Fixer through Pint in some way, let us know. Or hmu on Twitter if you want 🙂

**Comment by Jubeki** [comment]
@keradus 
I'd like to apolgize at this point, because this was an error on my part and has nothing to do with the laravel team.

While I was working on this, it seems like I was trying to clean up the code a bit and only read "MIT-License", which resulted in me deleting the copyright information. I am sorry about that.

If you want to contact me about that topic, please do that via contact@julius-kiekbusch.de

**Comment by keradus** [comment]
Thanks for prompt action, folks! 🙇🏻 

> I'd also like to point out that we handle tons of PR's daily and it's simply not possible for us to check the origin of code or license/copyright requirements of every single code that is sent in. We rely on our PR authors to be sensible and mindful about this. 

The author was bringing this aspect on their own in the PR that they raised ;) but I understand that it could get lost in tons of PRs.


> In general we also want to very much thank you and the rest of PHP CS Fixer of all the work you did and are still doing. I realise there has been some friction with the recent release of Pint but if you want we're always happy to discuss what we can do better in the future. If we can give more credit to PHP CS Fixer through Pint in some way, let us know. Or hmu on Twitter if you want 🙂

Sorry to hear that! I'm not tracking places where friction can happen, or maybe I'm too used to seeing wrappers over different SCA tools. From my side, I can only encourage to contribute directly to the main Fixer repo as well. I'm aware that creating something you own/control fully is faster and more exciting, while contributing to an old, mature repo may let one feel some burden of it, but later one is also allowing them to share the improvements with a bigger audience.

And who knows, maybe one day this package would be simply a configuration one while whole logic would be embedded in the Fixer repo.
