### ISSUE TITLE
Null Safe Operator removed

### ISSUE THREAD

**Issue by Progression** [laravel/pint#58]
- Pint Version: 0.2.1
- PHP Version: 8.1.3

### Description:
pint is removing the null safe operator whilst fixing other issues. So before applying pint I have the following:

```php
$result = $something?->else;
```

And after running pint

```php
$result = $somethingelse;
```

After running some tests it seems to happen reliably when fixing other issues, for instance when reformatting braces, as shown below...

### Steps To Reproduce:
1. Install a new Laravel app.
2. Created a new model "Test"
3. In Test.php created a new function:

```php
    public function foo($something) {
        $result = $something?->else;
    }
```

4. Run pint: ./vendor/bin/pint
5. Fixes one issue
<img width="996" alt="CleanShot 2022-06-28 at 13 41 57@2x" src="https://user-images.githubusercontent.com/942531/176181144-c61e4311-d0e2-4740-9fae-88ab86af1ca8.png">
6. Fixes the brace but also removes the null safe operator

```php
    public function foo($something)
    {
        $result = $somethingelse;
    }
```

If the brace was in the correct place to start with:

```php
    public function foo($something)
    {
        $result = $something?->else;
    }
```
Then running pint finds nothing to change or fix.

**Comment by nunomaduro** [comment]
You will need to share more information, as I can't reproduce the issue. Share your "pint.json", OS, etc.

**Comment by michalkortas** [comment]
I checked on Ubuntu 20.04, with default config. 

`<?php

class Test {
    public function foo($something) {
        $result = $something?->else;
    }

    public function bar($something)
    {
        $result = $something?->else;
    }
}
`

Output is the same as expected:

`   <?php
   
  -class Test {
  -    public function foo($something) {
  +class Test
  +{
  +    public function foo($something)
  +    {
           $result = $something?->else;
       }
   
  @@ -9,5 +11,4 @@
       {
           $result = $something?->else;
       }
  -
   }
`

**Comment by nunomaduro** [comment]
I will re-open the issue once we have more information about "pint.json", OS, etc.

**Comment by Progression** [comment]
So I never created a pint.json file. Just a clean install of Laravel and then install of pint through composer, nothing else (not added any explicit rules).
But I did just created one and added the standard laravel preset, as per the setup documentation but still the same end result.

I'm on MacOS 12.3 and an M1 Max processor.
Running everything through Docker / Sail
(But have also run direct on my mac and same issue)
Not sure if there is anything else that would be helpful?
