### ISSUE TITLE
Ability to use laravel preset with php-cs-fixer

### ISSUE THREAD

**Issue by ejunker** [laravel/pint#6]
As far as I know this is the only official Laravel code style preset. It would be nice if I could also use the rule preset with standard php-cs-fixer if I do not want to use the pint command. Pint makes things easy but since it is a layer on top of php-cs-fixer it does not have the full power and customization that php-cs-fixer allows.

For example, being able to reference `@Laravel` like this in `.php-cs-fixer.dist.php`
```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->name('*.php')
    ->ignoreDotFiles(true)
    ->ignoreVCS(true);

return (new PhpCsFixer\Config())
    ->setUsingCache(true)
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR12' => true,
        '@Laravel' => true,
    ])
    ->setFinder($finder);
```

**Comment by nunomaduro** [comment]
We will think about that. Thank you!
