### ISSUE TITLE
fixing unused variables in use statements on mac osx leads to trailing spaces

### ISSUE THREAD

**Issue by Jonnx** [laravel/pint#60]
- Pint Version: 0.2.1
- PHP Version: 8.1.6

### Description:
This happens on OSX (Intel). When pint removes unused variables in use statements of closures, it adds spaces before the commas. The validation then passes running `pint --test` and no files need fixing. However, when I run the same command as part of my CI/CD pipeline on a CircleCI image, the files are flagged as breaking style convention. 

### Steps To Reproduce:

original code
```php
$img->text($this->getUnicodeCharFromIcon($icon), ($size / 2) + $hoffset, ($size / 2) + $voffset, function ($font) use ($icon, $img, $size, $iconSize, $large_color, $small_color) {
            $font->file($this->getIconFontPath($icon));
            $font->size($iconSize);
            $font->color($small_color ?: $large_color);
            $font->align('center');
            $font->valign('center');
        });
```

run fix on osx
```
./vendor/bin/pint
```

fixed code for reference
```php
 $small_color = data_get($params, 'color') ?: null;
        $img->text($this->getUnicodeCharFromIcon($icon), ($size / 2) + $hoffset, ($size / 2) + $voffset, function ($font) use ($icon  , $iconSize, $large_color, $small_color) {
            $font->file($this->getIconFontPath($icon));
            $font->size($iconSize);
            $font->color($small_color ?: $large_color);
            $font->align('center');
            $font->valign('center');
        });
```

run test on osx (will pass)
```
./vendor/bin/pint --test
```

run fix on linux machine (fails)
```
./vendor/bin/pint --test
```

**Comment by Jonnx** [comment]
not a massive issue since these can be fixed manually and they don't re-appear. just figured I would highlight it since its a bit odd. big fan of the simplicity of this package though!

**Comment by nunomaduro** [comment]
Thanks - I guess we ignore that issue for now as it's not a big issue.
