### ISSUE TITLE
Support for Blade views files

### ISSUE THREAD

**Issue by olsza** [laravel/pint#64]
It would be helpful to add to PINT to correct views Blade files, e.g. as Tlint does...
Pint could fix e.g. :
- `{{$variable}}` -> `{{ $variable }}` or
- `@if(!$variable)` -> `@if (! $variable)` or
- 
```
@props([
    'size'=>'normal',
    'decorator' => false,
    'title' =>''
])
``` 
-> 
```
@props ([
    'size'      => 'normal',
    'decorator' => false,
    'title'     => '',
])
```
- etc.

**Comment by driesvints** [comment]
Heya, right now we're not planning on this sorry. We might do that in the future though!

**Comment by olsza** [comment]
> Heya, right now we're not planning on this sorry. We might do that in the future though!

thanks for answering ;)
