### ISSUE TITLE
Can we use Pint with VSCode for instance highlights

### ISSUE THREAD

**Issue by muath-ye** [laravel/pint#72]
Is there a way to highlight the code style issues while coding so I don't need to use terminal to update the code style.

**Comment by nunomaduro** [comment]
We are not sure. Sorry!

**Comment by benjibee** [comment]
@muath-ye it looks like there's already a few extension out there for VS Code. I'm currently using [this extension](https://github.com/open-southeners/vscode-laravel-pint) without any issues so far.
