### ISSUE TITLE
Separate Trait Imports

### ISSUE THREAD

**Issue by billriess** [laravel/pint#74]
Is it possible to separate the imports for traits? I couldn't find an option for this in php-cs-fixer but it may exist. Ideally, it would handle it similar to regular imports, one per `Use` statement.

**Comment by nunomaduro** [comment]
We are not sure. You can search here: https://mlocati.github.io/php-cs-fixer-configurator/.

**Comment by rawilk** [comment]
In case anyone is looking for the rule, you need to add this to your `pint.json` configuration to achieve this:

```json
{
    "single_trait_insert_per_statement": true
}
```

**Comment by billriess** [comment]
Thanks! Shouldn't this be default for PINT as it's a PSR-12 standard?

https://www.php-fig.org/psr/psr-12/#42-using-traits

**Comment by driesvints** [comment]
@billriess the default for Laravel is the Laravel preset, not the PSR-12 one.

**Comment by billriess** [comment]
Yes but I thought the Laravel preset was mostly based on PSR.
