### ISSUE TITLE
`if/else` statement spacing

### ISSUE THREAD

**Issue by jacoblockard99** [laravel/pint#76]
Currently, Laravel Pint converts this:

```php
<?php

if($something) {
  // ...
}
```

to:

```php
<?php

if ($something) {
  // ...
}
```

It appears that it is the `braces` rule that changes this, which is odd.

Is there any way to either disable this functionality, or better yet make Laravel Pint actually fix to the first one?

**Comment by nunomaduro** [comment]
You can disable / configure rules as detailed here: https://github.com/laravel/pint#rules.

**Comment by jacoblockard99** [comment]
Yes, I understand that.

However, it seems odd that the `braces` rule should control spacing around an `if` condition. Moreover, I would like to be able to set the first option as the correct option, not disable fixing it altogether.

Any ideas?
