### ISSUE TITLE
Conflict "single_import_per_statement" with "group_import" rule

### ISSUE THREAD

**Issue by PH7-Jack** [laravel/pint#77]
### Versions
- Pint Version: 0.2.3
- PHP Version: 8.1.8

### Description:
When I run the command `./vendor/bin/pint` I got an error

### Steps To Reproduce:
run in the terminal `./vendor/bin/pint`
My pint.json
```
{
    "preset": "laravel",
    "rules": {
        "@PSR2": true,
        "@PSR12": true,
        "group_import": true, 
        "array_indentation": true
    }
}

```

![image](https://user-images.githubusercontent.com/38913462/178125298-51818d59-db61-4630-9e3e-918093849d72.png)

**Comment by nunomaduro** [comment]
You can't use those two rules combined.

**Comment by PH7-Jack** [comment]
@nunomaduro I'm not using two rules combined, I'm using only one of them. 
Not works if I use **single_import_per_statement** or **group_import**. In the php-cs-fixer it works
I want to group all classes in the same namespace

**Comment by realodix** [comment]
```
{
    "preset": "laravel",
    "rules": {
        "@PSR2": true,
        "@PSR12": true,
        "single_import_per_statement": false,
        "group_import": true, 
        "array_indentation": true
    }
}
```
