### ISSUE TITLE
Integration with Laravel sail

### ISSUE THREAD

**Issue by vodnicearv** [laravel/pint#8]
it would be good to have a command such as
`sail pint`
or:
`sail artisan pint`

**Comment by nunomaduro** [comment]
We will think about that. Thank you!

**Comment by nunomaduro** [comment]
Once is tagged - you will be able to do `sail pint` too.

**Comment by Lumethys** [comment]
apparently `sail pint` works, but neither the document on Sail nor Pint mention this one. Perhaps new entry in the docs?
