### ISSUE TITLE
Latest version of pint is not taking care of CS-Fixer brace style 

### ISSUE THREAD

**Issue by hasinhayder** [laravel/pint#85]
- Pint Version: 0.2.4
- PHP Version: 8.1.8

### Description:
Previous versions of pint worked with the following configuration, correctly placing braces where they should be (K&R Style)

```json
{
    "preset": "laravel",
    "rules": {
        "simplified_null_return": true,
        "braces": {
            "position_after_functions_and_oop_constructs": "same"
        },
        "new_with_braces": {
            "anonymous_class": false,
            "named_class": false
        }
    }
}
```

But new pint doesn't respect this `position_after_functions_and_oop_constructs` value and always formats using Allman style, placing brace on the next line (which is same as `"position_after_functions_and_oop_constructs": "next"`

### Steps To Reproduce:

Edit your `pint.json` file in the root directory and add the following content, and then run ./vendor/bin/pint

```json
{
    "preset": "laravel",
    "rules": {
        "simplified_null_return": true,
        "braces": {
            "position_after_functions_and_oop_constructs": "same"
        },
        "new_with_braces": {
            "anonymous_class": false,
            "named_class": false
        }
    }
}
```

**Comment by nunomaduro** [comment]
Can you try using the latest version of Pint [v1.0.0](https://github.com/laravel/pint/releases/tag/v1.0.0), and let me know how it goes?

Keep in mind that you may have to override other options used here: https://github.com/laravel/pint/blob/77ffa26f8fde065ec183d55b96b42c0b05765755/resources/presets/laravel.php#L16.

**Comment by hasinhayder** [comment]
Update pint to v 1.0.0, it's still not working 

This is before running pint
![image](https://user-images.githubusercontent.com/490779/180160038-3b95c5ef-5d5b-4f28-8049-ee514762158d.png)

This is my `pint.json`
```json
{
    "preset": "laravel",
    "rules": {
        "simplified_null_return": true,
        "braces": {
            "position_after_functions_and_oop_constructs": "same"
        },
        "new_with_braces": {
            "anonymous_class": false,
            "named_class": false
        }
    }
}

```

running pint shows this 
![image](https://user-images.githubusercontent.com/490779/180160392-40cf2d44-a1ed-4636-95f8-bfadaeb0c912.png)


And this is the final output of the same `VaultController`

![image](https://user-images.githubusercontent.com/490779/180160487-a2dd9c7d-7b73-4670-9ac3-cdddfbb19abc.png)


It's not working

**Comment by hasinhayder** [comment]
But it works perfectly fine when I set the preset to `psr12`

![image](https://user-images.githubusercontent.com/490779/180160810-ce9267dc-b4cd-456b-9678-fefd203d4ed1.png)


```json
{
    "preset": "psr12",
    "rules": {
        "simplified_null_return": true,
        "braces": {
            "position_after_functions_and_oop_constructs": "same"
        },
        "new_with_braces": {
            "anonymous_class": false,
            "named_class": false
        }
    }
}

```

**Comment by hasinhayder** [comment]
> Can you try using the latest version of Pint [v1.0.0](https://github.com/laravel/pint/releases/tag/v1.0.0), and let me know how it goes?
> 
> Keep in mind that you may have to override other options used here:
> 
> https://github.com/laravel/pint/blob/77ffa26f8fde065ec183d55b96b42c0b05765755/resources/presets/laravel.php#L16
> 
> .

Previously it worked just with that one setting, and this brace style only needs that setting to be changed.

**Comment by hasinhayder** [comment]
@nunomaduro no update?

**Comment by dorianhouse** [comment]
Hi @hasinhayder, keep preset to laravel, but change the following:
```
"braces": {
	"allow_single_line_anonymous_class_with_empty_body": true,
	"allow_single_line_closure": true,
	"position_after_control_structures": "same",
	"position_after_functions_and_oop_constructs": "same",
	"position_after_anonymous_constructs": "same"
},
"curly_braces_position": {
	"control_structures_opening_brace": "same_line",
	"functions_opening_brace": "same_line",
	"anonymous_functions_opening_brace": "same_line",
	"classes_opening_brace": "same_line",
	"anonymous_classes_opening_brace": "same_line",
	"allow_single_line_empty_anonymous_classes": true,
	"allow_single_line_anonymous_functions": true
}
```

**Comment by hasinhayder** [comment]
Thank you @dorianhouse , much appreciated
