### ISSUE TITLE
A specific php-cs-fixer rule (method_chaining_indentation) not working with pint

### ISSUE THREAD

**Issue by introwit** [laravel/pint#91]
- Pint Version: 1.0.0
- PHP Version: 8.1.1

### Description:

- This specific `method_chaining_indentation` rule is not working when setup via the `pint.json` config file. It works when using this in the `.php-cs-fixer.php` file and running the cs fixer directly.  

### Steps To Reproduce:

- I have created a fresh installation of Laravel and [pushed the repo to GitHub](https://github.com/introwit/pinttest).

- It has both the [pint.json](https://github.com/introwit/pinttest/blob/master/pint.json) file and the [.php-cs-fixer.php](https://github.com/introwit/pinttest/blob/master/.php-cs-fixer.php) file as well. 

- I have added few lines in the [Controller here](https://github.com/introwit/pinttest/blob/master/app/Http/Controllers/Controller.php#L16-L18) to test this rule. If you have php-cs-fixer setup locally and run it, this is how the before and after looks like. It fixes as expected.

<img width="563" alt="Screenshot 2022-07-25 at 3 27 41 PM" src="https://user-images.githubusercontent.com/11228182/180750826-ae1b1698-d185-4c0d-8b28-ebdadb416217.png">

- But if I run pint, it does not fix it.

**Comment by nunomaduro** [comment]
Your JSON file is invalid. Try this:

```
{
    "rules": {
        "concat_space": {
            "spacing": "one"
        },
        "method_chaining_indentation": true
    }
}
```

**Comment by introwit** [comment]
That worked. Thank you :heart:
