### ISSUE TITLE
Parallel Fixer

### ISSUE THREAD

**Issue by billriess** [laravel/pint#93]
It would be nice if Pint could run in parallel. Currently, you can do this in `php-cs-fixer` using a pipe to `xargs`. There is some documentation on this found in this commit:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5390/files#diff-e2f32bf1fe37315337b25b0d5efe2a8dde59b0f5ea2c3d6fddcf3f8b6d0fe9d1R150

**Comment by nunomaduro** [comment]
Thanks for your suggestion - we will take a look.

**Comment by gazzoy** [comment]
Just curious, any plans to supporting this?
