### ISSUE TITLE
IDE's integration

### ISSUE THREAD

**Issue by VladChekunov** [laravel/pint#99]
How can I use Pint inside of IDE like a PHPStorm or a VSCode?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by chrillep** [comment]
for VSCode i guess -> https://marketplace.visualstudio.com/search?term=%22laravel%20pint%22&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by chrillep** [comment]
for phpstorm i believe the fixers need to be merged into php-cs-fixer upstream to get full functionality from that integration in the IDE
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6441
